spring:
  application:
    name: sessionTest

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/session_test
    username: root
    password: 1111

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  devtools:
    restart:
      enabled: false
